// Generated by https://quicktype.io

export interface PokemonListResponse {
  count: number;
  next: null;
  previous: string;
  results: BasicPokemonInfo[];
}

export interface BasicPokemonInfo {
  name: string;
  url: string;
}
